"""Comms tools — ticket filing + timeline rendering.

`file_ticket` writes a REAL artifact to disk (tickets/<id>.json) so "filed a
ticket" is a verifiable file, not a claim. Slack posting lives in
services/slack.py; RCA prose is generated by the Comms agent via Gemini.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from backend.config import REPO_ROOT
from backend.models import Incident

TICKETS_DIR = REPO_ROOT / "tickets"


@dataclass
class Ticket:
    id: str
    path: str
    url: str


def file_ticket(incident: Incident, rca_summary: str) -> Ticket:
    TICKETS_DIR.mkdir(exist_ok=True)
    ticket_id = f"OPS-{incident.id.split('_')[-1][:6].upper()}"
    body: dict[str, Any] = {
        "ticket_id": ticket_id,
        "incident_id": incident.id,
        "title": f"[{incident.severity.value if incident.severity else 'SEV?'}] "
                 f"{incident.service}: {incident.probable_cause or 'incident'}",
        "status": "Resolved" if incident.resolved_at else "Open",
        "severity": incident.severity.value if incident.severity else None,
        "service": incident.service,
        "probable_cause": incident.probable_cause,
        "confidence": incident.confidence,
        "remediation": incident.remediation_plan.model_dump() if incident.remediation_plan else None,
        "approved_by": incident.approved_by,
        "rca_summary": rca_summary,
        "detected_at": incident.detected_at,
        "resolved_at": incident.resolved_at,
    }
    path = TICKETS_DIR / f"{ticket_id}.json"
    path.write_text(json.dumps(body, indent=2), encoding="utf-8")
    return Ticket(id=ticket_id, path=str(path), url=f"https://tickets.corp.dev/{ticket_id}")


def resolution_minutes(incident: Incident) -> float:
    if not incident.resolved_at:
        return 0.0
    return round((incident.resolved_at - incident.detected_at) / 60000.0, 1)
